services:
  - type: web
    name: Grandkojo's Portfolio
    runtime: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install && npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: PHP_VERSION
        value: 8.2
